# Remote Setting
baseurl: "/" #https://github.com/pmarsceill/just-the-docs/issues/148
url: "GSDHUB.Dev"
repository: gsd/GSDHub.Dev

title: GSD

description: Your Hub for Getting Shit Done

permalink: pretty

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# Google Analytics Tracking (optional)
# e.g, UA-161584770-1
ga_tracking: UA-161584770-1
plugins:  # not for this theme, but just to be safe, unless it breaks somthing?
  - jekyll-seo-tag # not for this theme, but just to be safe, unless it breaks somthing?
google_analytics: UA-161584770-1 # not for this theme, but just to be safe, unless it breaks somthing?

footer_content: "Copyright &copy; 2019-2020 Paul Oliver. Distributed by an <a href="https://github.com/GSD/GSDHub.Dev/blob/master/LICENSE">MIT license.</a>"

aux_links:
  "GSD":
    - "//github.com/GSD/GSDHub.Dev"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

